#!/usr/bin/env bash

# Create symliks
## Git
ln -sFv $PWD/git/gitconfig ~/.gitconfig
ln -sFv $PWD/git/githelpers ~/.githelpers
ln -sFv $PWD/git/gitignore ~/.gitignore

## Ruby
ln -sFv $PWD/ruby/gemrc ~/.gemrc
ln -sFv $PWD/ruby/irbrc ~/.irbrc
ln -sFv $PWD/ruby/pryrc ~/.pryrc
ln -sFv $PWD/ruby/bundle_config ~/.bundle/config

## Elixir
ln -sFv $PWD/elixir/iex.exs ~/.iex.exs

## Vim
mkdir -pv $HOME/.vim/colors
ln -sFv $PWD/vim/vimrc ~/.vimrc
ln -sFv $PWD/vim/vimrc.bundles ~/.vimrc.bundles
ln -sFv $PWD/vim/vimrc_background ~/.vimrc_background

## Tmux
ln -sFv $PWD/tmux/tmux.conf ~/.tmux.conf

## The silver searcher
ln -sFv $PWD/ag/agignore ~/.agignore

## Ctags
ln -sFv $PWD/ctags/ctags ~/.ctags


# Install Vim plugins
if [ ! -d $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi

vim +BundleInstall +qall


# Install/update Homebrew
if [ ! -d /usr/local/Cellar ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Had to run this to make Homebrew work again after a `homebrew/versions` was deprecated
  # git -C "$(brew --repo homebrew/core)" fetch --unshallow
  
  brew install zsh openssl git hub rbenv ruby-build node yarn tmux qt phantomjs the_silver_searcher mysql@5.6 postgresql redis percona-toolkit elasticsearch ctags-exuberant libsass
else
  brew update
  brew upgrade
fi


# Setup Oh-my-zsh
sudo chsh -s $(which zsh) $(whoami)

if [ ! -d $HOME/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

mkdir -pv $HOME/.oh-my-zsh/custom/plugins/sebasoga
cp -fv $PWD/zsh/sebasoga.plugin.zsh $HOME/.oh-my-zsh/custom/plugins/sebasoga/sebasoga.plugin.zsh

sed -i '' "s/^plugins=.*$/plugins=(brew bundler capistrano git rails rake rbenv ruby sebasoga)/g" $HOME/.zshrc

## Load rbenv automatically
if ! grep -e "^eval \"\$(rbenv init -)\"" $HOME/.zshrc ; then
  echo '' >> $HOME/.zshrc
  echo '# Added by doftiles installer for rbenv' >> $HOME/.zshrc
  echo 'eval "$(rbenv init -)"' >> $HOME/.zshrc
fi

## Set the Golang path
if ! grep -e "^export GOPATH=\$HOME/go" $HOME/.zshrc ; then
  echo '' >> $HOME/.zshrc
  echo '# Added by doftiles installer for Go' >> $HOME/.zshrc
  echo 'export GOPATH=$HOME/go' >> $HOME/.zshrc
fi

## Set the GPG signingkey
if ! grep -e "^export GPG_TTY=\$(tty)" $HOME/.zshrc ; then
  echo '' >> $HOME/.zshrc
  echo '# GPG' >> $HOME/.zshrc
  echo 'export GPG_TTY=$(tty)' >> $HOME/.zshrc
fi

# Configure base16-shell
if [ ! -d $HOME/.config/base16-shell ]; then
  git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
fi

if ! grep -e "^BASE16_SHELL" $HOME/.zshrc ; then
  echo '' >> $HOME/.zshrc
  echo '# Base16 (iTerm2 theme colors)' >> $HOME/.zshrc
  echo 'BASE16_SHELL=${HOME}/.config/base16-shell/' >> $HOME/.zshrc
  echo '[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"' >> $HOME/.zshrc
fi

zsh
